name: Go

on: push

jobs:
  the-works:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Lint
      uses: golangci/golangci-lint-action@v3

    - name: Test
      run: go test -cover -v ./...

    - name: Build
      run: go build -v ./...
