name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout

    - name: Set up Go
      uses: actions/setup-go

    - name: Lint
      uses: golangci/golangci-lint-action

    - name: Test
      run: go test -cover -v ./...

    - name: Build
      run: go build -v ./...
